"""Added server-defaults to the created_at and updated_at columns

Revision ID: 20565758206d
Revises: b0afb77a8dd2
Create Date: 2024-10-21 13:57:15.484262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20565758206d'
down_revision = 'b0afb77a8dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('created_at', server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at', server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.alter_column('created_at', server_default=None)
        batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###
